#服务端口
server:
  port: 8080

# druid配置   
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:oracle:thin:@//192.168.18.150:1521/orclpdb
    #jdbc-url: jdbc:oracle:thin:@//192.168.6.121:1521/orclpdb
    url: jdbc:oracle:thin:@//192.168.6.121:1521/orclpdb
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: LC_T
    password: LC_T
    druid:
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      filter:
        stat:
          enabled: true
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true 
      stat-view-servlet:
        enabled: true
        reset-enable: false
      aop-patterns: com.nqmysb.practice.controller.*.*,com.nqmysb.practice.service.*.*
      
 # 工作流
    activiti:
      # 校验resource/process/下的流程模型
      #check-process-definitions: false
      # 校验用户信息表是否存在
      #db-identity-used: true
      # 自动生成Activiti相关表 第一次生成后建议关闭提高运行速度
      #database-schema-update: true
      # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
      #history-level: full   
      
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml

